name: clima
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  geolocator: ^6.2.0
  http: ^0.13.0
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: assets/fonts/SpartanMB-Black.otf
      weight: 900
